version: "3.4"

services:
  fb-comment-tracking-app:
    image: fb-comment-tracking-app
    build: .
    restart: always
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
